-- AlterTable
ALTER TABLE "Post" ADD COLUMN "summary" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Post" ADD COLUMN "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Post" ADD COLUMN "imageUrl" TEXT;

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "summary" DROP DEFAULT;
ALTER TABLE "Post" ALTER COLUMN "publishedAt" DROP DEFAULT;
